import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Nature Heaven Trek & Expedition",
    short_name: "Nature Heaven",
    description:
      "Nepal's leading agency for 100% private, personalized trekking packages in Everest, Annapurna, and Manaslu regions.",
    start_url: "/",
    display: "standalone",
    background_color: "#f8f5f0",
    theme_color: "#1a3c2e",
    icons: [
      {
        src: "/favicon.ico",
        sizes: "any",
        type: "image/x-icon",
      },
      // Generated by app/icon1.tsx — 192×192
      {
        src: "/icon1",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      // Generated by app/icon2.tsx — 512×512
      {
        src: "/icon2",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      // Generated by app/apple-icon.tsx — 180×180 for iOS home-screen
      {
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
      },
    ],
  };
}
