/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    roles: Role;
    siteSettings: SiteSetting;
    navbarSettings: NavbarSetting;
    footerSettings: FooterSetting;
    regions: Region;
    treks: Trek;
    blogPosts: BlogPost;
    teamMembers: TeamMember;
    testimonials: Testimonial;
    gallery: Gallery;
    faqs: Faq;
    departures: Departure;
    bookings: Booking;
    inquiries: Inquiry;
    payments: Payment;
    media: Media;
    pages: Page;
    contactPages: ContactPage;
    blogSettings: BlogSetting;
    companyPages: CompanyPage;
    homepageSettings: any;
    regionsPageSettings: any;
    countriesPageSettings: any;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navbarSettings: NavbarSettingsSelect<false> | NavbarSettingsSelect<true>;
    footerSettings: FooterSettingsSelect<false> | FooterSettingsSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    treks: TreksSelect<false> | TreksSelect<true>;
    blogPosts: BlogPostsSelect<false> | BlogPostsSelect<true>;
    teamMembers: TeamMembersSelect<false> | TeamMembersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    departures: DeparturesSelect<false> | DeparturesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    contactPages: ContactPagesSelect<false> | ContactPagesSelect<true>;
    blogSettings: BlogSettingsSelect<false> | BlogSettingsSelect<true>;
    companyPages: CompanyPagesSelect<false> | CompanyPagesSelect<true>;
    homepageSettings: any;
    regionsPageSettings: any;
    countriesPageSettings: any;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Upload a custom profile picture.
   */
  avatar?: (number | null) | Media;
  role: 'admin' | 'editor' | 'viewer' | 'custom';
  /**
   * Select a custom role managed in the Roles collection.
   */
  customRole?: (number | null) | Role;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive text for accessibility/SEO.
   */
  alt: string;
  /**
   * Categorize files to easily filter them in the media library.
   */
  category: 'uncategorized' | 'trek_covers' | 'blog_covers' | 'gallery_photos' | 'team_photos';
  /**
   * Keywords/tags for quick search.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  name: string;
  permissions?: {
    treks_read?: boolean | null;
    treks_create?: boolean | null;
    treks_update?: boolean | null;
    treks_delete?: boolean | null;
    regions_read?: boolean | null;
    regions_create?: boolean | null;
    regions_update?: boolean | null;
    regions_delete?: boolean | null;
    departures_read?: boolean | null;
    departures_create?: boolean | null;
    departures_update?: boolean | null;
    departures_delete?: boolean | null;
    blogPosts_read?: boolean | null;
    blogPosts_create?: boolean | null;
    blogPosts_update?: boolean | null;
    blogPosts_delete?: boolean | null;
    pages_read?: boolean | null;
    pages_create?: boolean | null;
    pages_update?: boolean | null;
    pages_delete?: boolean | null;
    faqs_read?: boolean | null;
    faqs_create?: boolean | null;
    faqs_update?: boolean | null;
    faqs_delete?: boolean | null;
    gallery_read?: boolean | null;
    gallery_create?: boolean | null;
    gallery_update?: boolean | null;
    gallery_delete?: boolean | null;
    testimonials_read?: boolean | null;
    testimonials_create?: boolean | null;
    testimonials_update?: boolean | null;
    testimonials_delete?: boolean | null;
    teamMembers_read?: boolean | null;
    teamMembers_create?: boolean | null;
    teamMembers_update?: boolean | null;
    teamMembers_delete?: boolean | null;
    bookings_read?: boolean | null;
    bookings_create?: boolean | null;
    bookings_update?: boolean | null;
    bookings_delete?: boolean | null;
    inquiries_read?: boolean | null;
    inquiries_create?: boolean | null;
    inquiries_update?: boolean | null;
    inquiries_delete?: boolean | null;
    payments_read?: boolean | null;
    payments_create?: boolean | null;
    payments_update?: boolean | null;
    payments_delete?: boolean | null;
    siteSettings_read?: boolean | null;
    siteSettings_update?: boolean | null;
    media_read?: boolean | null;
    media_create?: boolean | null;
    media_update?: boolean | null;
    media_delete?: boolean | null;
    users_read?: boolean | null;
    users_create?: boolean | null;
    users_update?: boolean | null;
    users_delete?: boolean | null;
    roles_read?: boolean | null;
    roles_create?: boolean | null;
    roles_update?: boolean | null;
    roles_delete?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  logo?: string | null;
  /**
   * MP4 URL or YouTube Link for the homepage background video.
   */
  heroVideoUrl?: string | null;
  heroImage?: (number | null) | Media;
  heroHeadline: string;
  heroSubheadline?: string | null;
  stats?: {
    clients?: string | null;
    years?: string | null;
    treks?: string | null;
    rating?: string | null;
  };
  contactInfo?: {
    phone?: string | null;
    whatsapp?: string | null;
    email?: string | null;
    address?: string | null;
    mapCoordinates?: string | null;
  };
  emergencyNumbers?:
    | {
        number?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?: {
    youtube?: string | null;
    instagram?: string | null;
    facebook?: string | null;
    tiktok?: string | null;
  };
  affiliations?:
    | {
        name?: string | null;
        logo?: (number | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  headerSettings?: {
    expertName?: string | null;
    expertPhone?: string | null;
    expertWhatsApp?: string | null;
    quickEmail?: string | null;
  };
  footerSettings?: {
    bioText?: string | null;
    nepalHeadOfficeAddress?: string | null;
    nepalHeadOfficePhone?: string | null;
    ukBranchOfficeAddress?: string | null;
    ukBranchOfficePhone?: string | null;
    governmentRegNo?: string | null;
  };
  /**
   * YouTube videos shown in the Himalayan Trek Experience section. Paste the 11-char ID or the full YouTube URL.
   */
  videoGallery?:
    | {
        /**
         * Can be the full YouTube URL or just the video ID. E.g. h1F7Tj2_H0Q
         */
        youtubeId: string;
        title: string;
        trekName?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Select the top 5 treks to display in the navbar dropdown under "Top 5 Treks".
   */
  top5Treks?: (number | Trek)[] | null;
  paymentSettings?: {
    enableStripe?: boolean | null;
    enablePaypal?: boolean | null;
    enableLocalWallets?: boolean | null;
    enableBankTransfer?: boolean | null;
    enableBookNowPayLater?: boolean | null;
    /**
     * Set to 0 to completely hide the Advance Deposit option.
     */
    advancePaymentPercentage?: number | null;
  };
  blogsPageSettings?: {
    coverImage?: (number | null) | Media;
    title?: string | null;
    subtitle?: string | null;
  };
  /**
   * Manage the review scores/counts displayed on the homepage.
   */
  reviewPlatforms?:
    | {
        name: string;
        rating: string;
        maxRating: string;
        reviewsCount: string;
        badgeText?: string | null;
        stars: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Select travel info pages to feature in a card list on the homepage.
   */
  featuredTravelInfo?: (number | Page)[] | null;
  allowIndexing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage all trek packages. Each section below corresponds to a section on the trek detail page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treks".
 */
export interface Trek {
  id: number;
  /**
   * Full trek name, e.g. "Everest Base Camp Trek – 14 Days"
   */
  title: string;
  /**
   * URL identifier, no spaces. e.g. "everest-base-camp-trek-14"
   */
  slug: string;
  region: number | Region;
  difficulty: 'easy' | 'moderate' | 'hard' | 'extreme';
  /**
   * Original price in USD per person
   */
  price: number;
  /**
   * Sale/discounted price in USD (leave empty if no discount)
   */
  discountedPrice?: number | null;
  /**
   * Total number of days (e.g. 14)
   */
  duration: number;
  /**
   * Highest point in meters (e.g. 5364)
   */
  maxAltitude: number;
  /**
   * Max group size (e.g. 12)
   */
  groupSize?: number | null;
  /**
   * Where the trek starts (e.g. Lukla)
   */
  startPoint?: string | null;
  /**
   * Where the trek ends (e.g. Lukla)
   */
  endPoint?: string | null;
  /**
   * Best months to trek (e.g. "Spring (Mar–May) & Autumn (Sep–Nov)")
   */
  bestSeason?: string | null;
  /**
   * Accommodation type (e.g. "Teahouses & 3-Star Hotels in KTM")
   */
  accommodationType?: string | null;
  /**
   * Meals provided (e.g. "Breakfast, Lunch & Dinner on trek")
   */
  mealsIncluded?: string | null;
  isBestSeller?: boolean | null;
  /**
   * Key selling points shown as a bullet list. Add one highlight per row.
   */
  highlights?:
    | {
        /**
         * e.g. "Stand at Everest Base Camp (5,364m)"
         */
        highlight: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Main trek description. Use headings, bold text, and paragraphs for a well-structured overview.
   */
  overview: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Custom title for this card, e.g. "Lukla Flight Information" or "Pokhara Flight Information" or "Flight Information". Defaults to "Lukla Flight Information".
   */
  flightInfoTitle?: string | null;
  /**
   * Explain flight details, seasonal variations, weather delays, and buffer day recommendations.
   */
  flightInfo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Explain the pre-trek online briefing process — what it covers, when it happens, how to join (WhatsApp/Zoom).
   */
  briefingInfo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Main cover image shown at the top of the page. Use a landscape photo, minimum 1200px wide.
   */
  heroImage?: (number | null) | Media;
  /**
   * Upload a static route map (JPG/PNG/WebP). If empty, the interactive GPS map will be used instead.
   */
  mapImage?: (number | null) | Media;
  /**
   * Upload additional trek photos (up to 20 recommended). They appear in the gallery grid.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Paste the full YouTube URL or just the 11-character video ID (e.g. fAsw_vB3JpI). The video will be embedded on the trek page.
   */
  youtubeVideoId?: string | null;
  dayByDayItinerary?:
    | {
        /**
         * Day number (1, 2, 3...)
         */
        day: number;
        /**
         * Day title, e.g. "Fly to Lukla & Trek to Phakding (2,652m)"
         */
        title: string;
        /**
         * Key location name (e.g. Lukla) to show as a header badge
         */
        location?: string | null;
        /**
         * Distance walked, e.g. "8.5 km (5.3 miles)"
         */
        distance?: string | null;
        /**
         * Altitude at end of day in meters, e.g. 2652
         */
        altitude?: number | null;
        /**
         * e.g. 3 hours
         */
        trekDuration?: string | null;
        /**
         * e.g. 40/20 Minutes
         */
        flightHours?: string | null;
        /**
         * What happens on this day. 2–4 sentences is ideal.
         */
        description: string;
        /**
         * Where you sleep, e.g. "Standard Teahouse"
         */
        accommodation?: string | null;
        /**
         * Meals provided, e.g. "B, L, D" or "Breakfast only"
         */
        meals?: string | null;
        /**
         * Add photos or YouTube videos for this specific itinerary day.
         */
        media?:
          | {
              type: 'image' | 'video';
              /**
               * Select an image from library or upload one.
               */
              image?: (number | null) | Media;
              /**
               * Paste YouTube watch URL or 11-character video ID.
               */
              youtubeUrl?: string | null;
              /**
               * Optional short caption or title for this media.
               */
              title?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  inclusions?:
    | {
        heading: string;
        icon?:
          | (
              | 'transport'
              | 'accommodation'
              | 'food'
              | 'guide'
              | 'permits'
              | 'insurance'
              | 'visa'
              | 'equipment'
              | 'personal'
              | 'info'
            )
          | null;
        points?:
          | {
              point: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  exclusions?:
    | {
        heading: string;
        icon?:
          | (
              | 'transport'
              | 'accommodation'
              | 'food'
              | 'guide'
              | 'permits'
              | 'insurance'
              | 'visa'
              | 'equipment'
              | 'personal'
              | 'info'
            )
          | null;
        points?:
          | {
              point: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Suggested categories: Headwear, Clothing Layers, Footwear & Handwear, Personal Gear, Toiletries & Medicines.
   */
  packingList?:
    | {
        /**
         * Category name, e.g. "Clothing & Layers"
         */
        category: string;
        items?:
          | {
              /**
               * e.g. "Down Jacket (rated to -10°C, provided if needed)"
               */
              item: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tip: Good topics include — Accommodation, Food & Meals, Water & Hydration, Luggage Limits, Altitude Safety, Travel Insurance, Guide & Porters, Tipping Guidelines, Electricity & WiFi, Packing Tips.
   */
  tripInfoSections?:
    | {
        /**
         * Topic title, e.g. "Accommodation & Lodging"
         */
        title: string;
        icon?:
          | (
              | 'accommodation'
              | 'food'
              | 'water'
              | 'luggage'
              | 'flights'
              | 'insurance'
              | 'visa'
              | 'health'
              | 'helicopter'
              | 'guide'
              | 'weather'
              | 'electricity'
              | 'shower'
              | 'money'
              | 'tipping'
              | 'info'
            )
          | null;
        /**
         * Content for this topic. You can use bold text, bullet lists, and paragraphs.
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Optional image or chart to display in this section (e.g. Route Map, Altitude Chart, packing diagram).
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Add each key location on the route. The map will draw a line through them in order.
   */
  gpsCoordinates?:
    | {
        /**
         * e.g. 27.9878
         */
        lat: number;
        /**
         * e.g. 86.9250
         */
        lng: number;
        /**
         * e.g. "Namche Bazaar"
         */
        label: string;
        /**
         * Optional: altitude in meters
         */
        altitude?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Example: 1 person = $1,500 | 2–3 persons = $1,440 | 4–7 persons = $1,380
   */
  groupDiscounts?:
    | {
        /**
         * Min group size (e.g. 1)
         */
        minPersons: number;
        /**
         * Max group size (e.g. 3)
         */
        maxPersons: number;
        /**
         * Price per person in USD (e.g. 1440)
         */
        pricePerPerson: number;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        /**
         * The question travellers often ask
         */
        question: string;
        category?:
          | (
              | 'general'
              | 'prep_fitness'
              | 'permits'
              | 'insurance_visa'
              | 'guides_staff'
              | 'accommodation_facilities'
              | 'food_drinks'
              | 'weather_seasons'
              | 'health_safety'
              | 'packing_gear'
              | 'booking_payments'
              | 'transportation_flights'
            )
          | null;
        /**
         * Clear, helpful answer. 2–4 sentences is ideal.
         */
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Page title for Google (50–60 chars). Leave blank to auto-use the trek title.
   */
  metaTitle?: string | null;
  /**
   * Short description for Google search results (140–160 chars). Leave blank to auto-use the overview.
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  coverImage?: (number | null) | Media;
  mapCenter?: {
    lat?: number | null;
    lng?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * The URL path for this page (e.g. weather-and-climate). Auto-generated from title if left blank.
   */
  slug: string;
  /**
   * Used for list previews, cards, and meta tags.
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Large image displayed at the top of the page behind the title.
   */
  heroImage?: (number | null) | Media;
  /**
   * Leave blank to use the page title.
   */
  seoTitle?: string | null;
  /**
   * Leave blank to use the excerpt.
   */
  seoDescription?: string | null;
  showInNavbar?: boolean | null;
  navbarCategory?: ('essential' | 'safety' | 'destinations') | null;
  /**
   * Lower numbers appear first in the column.
   */
  navbarOrder?: number | null;
  /**
   * Select related trekking itineraries to display as promotional cards on this page.
   */
  relatedTreks?: (number | Trek)[] | null;
  /**
   * Link PDFs, visa guidelines, or maps for travelers to download.
   */
  documents?: (number | Media)[] | null;
  videos?:
    | {
        title: string;
        /**
         * Paste watch URL or 11-char ID.
         */
        youtubeUrl: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure global navigation headers, brand assets, and multi-level dropdowns.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbarSettings".
 */
export interface NavbarSetting {
  id: number;
  siteName: string;
  logo?: (number | null) | Media;
  /**
   * Add, reorder, show/hide, or delete navbar menu sections.
   */
  navigationMenu?:
    | {
        title: string;
        type: 'dropdown' | 'single-link';
        href?: string | null;
        dropdownStyle?:
          | ('regions-grid' | 'travel-info' | 'contact-pages' | 'company-pages' | 'treks-list' | 'custom-links')
          | null;
        /**
         * Select treks (e.g. Top 15) to include in this dropdown.
         */
        featuredTreks?: (number | Trek)[] | null;
        customLinks?:
          | {
              label: string;
              href: string;
              hide?: boolean | null;
              id?: string | null;
            }[]
          | null;
        hide?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure dynamic footer menus, emergency contacts, branch addresses, accepted payments, and partner affiliations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footerSettings".
 */
export interface FooterSetting {
  id: number;
  siteName: string;
  logo?: (number | null) | Media;
  backgroundImage?: (number | null) | Media;
  bioText?: string | null;
  newsletterTitle?: string | null;
  emergencyTitle?: string | null;
  emergencyNumbers?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  whatsappNumber?: string | null;
  emails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  nepalOfficeAddress?: string | null;
  nepalOfficePhone?: string | null;
  ukOfficeAddress?: string | null;
  ukOfficePhone?: string | null;
  navigationMenu?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  acceptedPayments?: {
    enableSectigo?: boolean | null;
    enablePaypal?: boolean | null;
    enableMastercard?: boolean | null;
    enableVisa?: boolean | null;
    enableSwift?: boolean | null;
  };
  affiliations?:
    | {
        name: string;
        logo?: (number | null) | Media;
        url: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?: {
    youtube?: string | null;
    instagram?: string | null;
    facebook?: string | null;
    tiktok?: string | null;
  };
  governmentRegNo?: string | null;
  copyrightNotice?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts".
 */
export interface BlogPost {
  id: number;
  coverImage: number | Media;
  title: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * A brief summary of the blog post shown on lists and category cards.
   */
  excerpt: string;
  /**
   * Search engine and social sharing settings for this post.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaImage?: (number | null) | Media;
  };
  status: 'draft' | 'published';
  publishedAt: string;
  slug: string;
  author: number | TeamMember;
  /**
   * E.g. Trekking Guides, Travel Info, Packing Tips
   */
  category: string;
  isFeatured?: boolean | null;
  /**
   * Keywords/tags for quick search.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  relatedTreks?: (number | Trek)[] | null;
  /**
   * Auto-calculated from post body.
   */
  wordCount?: number | null;
  /**
   * Auto-calculated from post body.
   */
  readTime?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teamMembers".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  photo?: (number | null) | Media;
  bio?: string | null;
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  clientName: string;
  country: string;
  rating: number;
  reviewText: string;
  trek?: (number | null) | Trek;
  date?: string | null;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  category: 'trekking' | 'sightseeing' | 'people_culture' | 'landscapes' | 'accommodation_meals' | 'others';
  /**
   * Upload or choose an image from media library.
   */
  image: number | Media;
  caption?: string | null;
  /**
   * Link this photo to a specific trek (optional).
   */
  trek?: (number | null) | Trek;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Used for sorting FAQs on pages. Smaller numbers appear first.
   */
  order?: number | null;
  /**
   * Categorize this FAQ to help organize lists.
   */
  category:
    | 'general'
    | 'prep_fitness'
    | 'permits'
    | 'insurance_visa'
    | 'guides_staff'
    | 'accommodation_facilities'
    | 'food_drinks'
    | 'weather_seasons'
    | 'health_safety'
    | 'packing_gear'
    | 'booking_payments'
    | 'transportation_flights'
    | 'everest'
    | 'annapurna'
    | 'manaslu'
    | 'langtang'
    | 'ganesh-himal'
    | 'mustang'
    | 'kanchenjunga'
    | 'makalu'
    | 'dolpa'
    | 'tour-in-nepal'
    | 'expedition-in-nepal'
    | 'peak-climbing-in-nepal'
    | 'jungle-safari-in-nepal'
    | 'river-rafting-in-nepal'
    | 'bungee-jumping-in-nepal'
    | 'paragliding-in-nepal';
  /**
   * Optional: Select specific treks where this FAQ will appear. If empty, this FAQ is global.
   */
  treks?: (number | Trek)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departures".
 */
export interface Departure {
  id: number;
  trek: number | Trek;
  startDate: string;
  endDate: string;
  availableSeats: number;
  bookedSeats: number;
  status: 'available' | 'limited' | 'sold_out' | 'cancelled';
  priceOverride?: number | null;
  isGuaranteed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  bookingId: string;
  trek: number | Trek;
  departure?: (number | null) | Departure;
  startDate: string;
  endDate: string;
  travelersCount: number;
  travelers?:
    | {
        firstName: string;
        lastName: string;
        email?: string | null;
        nationality: string;
        gender: 'male' | 'female' | 'other';
        dob: string;
        passportNumber?: string | null;
        passportExpiry?: string | null;
        id?: string | null;
      }[]
    | null;
  customerDetails: {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    country: string;
  };
  basePrice: number;
  discount?: number | null;
  tax?: number | null;
  totalPrice: number;
  paymentType: 'full' | 'advance_10' | 'pay_later';
  paymentStatus: 'unpaid' | 'partial' | 'paid' | 'refunded';
  bookingStatus: 'pending' | 'confirmed' | 'cancelled' | 'completed';
  adminRemarks?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  type: 'contact' | 'plan_trip' | 'booking_enquiry' | 'newsletter' | 'country_inquiry';
  name?: string | null;
  email: string;
  phone?: string | null;
  country?: string | null;
  subject?: string | null;
  trek?: (number | null) | Trek;
  startDate?: string | null;
  travelers?: number | null;
  message?: string | null;
  status: 'new' | 'contacted' | 'resolved' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  booking: number | Booking;
  paymentId: string;
  amount: number;
  method: 'stripe' | 'paypal' | 'esewa' | 'khalti' | 'bank_transfer';
  status: 'pending' | 'success' | 'failed' | 'refunded';
  transactionDetails?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPages".
 */
export interface ContactPage {
  id: number;
  title: string;
  /**
   * The URL path for this page (e.g. payment-methods). Auto-generated from title if left blank.
   */
  slug: string;
  /**
   * Used for list previews, cards, and meta tags.
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Large image displayed at the top of the page behind the title.
   */
  heroImage?: (number | null) | Media;
  /**
   * Leave blank to use the page title.
   */
  seoTitle?: string | null;
  /**
   * Leave blank to use the excerpt.
   */
  seoDescription?: string | null;
  /**
   * Select related trekking itineraries to display as promotional cards on this page.
   */
  relatedTreks?: (number | Trek)[] | null;
  /**
   * Link PDFs, visa guidelines, or maps for travelers to download.
   */
  documents?: (number | Media)[] | null;
  videos?:
    | {
        title: string;
        /**
         * Paste watch URL or 11-char ID.
         */
        youtubeUrl: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the blogs listing page header title, subtitle, and hero cover image.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogSettings".
 */
export interface BlogSetting {
  id: number;
  /**
   * Banner photo for the blog page header.
   */
  coverImage: number | Media;
  title: string;
  subtitle: string;
  guideSettings?: {
    title: string;
    subtitle: string;
    badgeText: string;
    footerText: string;
    description: string;
    pdfFile: number | Media;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companyPages".
 */
export interface CompanyPage {
  id: number;
  title: string;
  /**
   * The URL path for this page (e.g. about-us, why-us, csr). Auto-generated from title if left blank.
   */
  slug: string;
  /**
   * Used for list previews, cards, and meta tags.
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Large image displayed at the top of the page behind the title.
   */
  heroImage?: (number | null) | Media;
  /**
   * Leave blank to use the page title.
   */
  seoTitle?: string | null;
  /**
   * Leave blank to use the excerpt.
   */
  seoDescription?: string | null;
  /**
   * Select related trekking itineraries to display as promotional cards on this page.
   */
  relatedTreks?: (number | Trek)[] | null;
  /**
   * Link PDFs, visa guidelines, or maps for travelers to download.
   */
  documents?: (number | Media)[] | null;
  /**
   * Add photos/images of government registration certificates, licenses, and tax documents (displays on the Legal Documents page).
   */
  legalCertificates?:
    | {
        title: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Add team members directly inside this page document (displays on the Our Team page).
   */
  teamMembers?:
    | {
        name: string;
        role: string;
        photo?: (number | null) | Media;
        bio?: string | null;
        socialLinks?: {
          facebook?: string | null;
          instagram?: string | null;
          linkedin?: string | null;
          twitter?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  videos?:
    | {
        title: string;
        /**
         * Paste watch URL or 11-char ID.
         */
        youtubeUrl: string;
        id?: string | null;
      }[]
    | null;
  csrQuote?: {
    text?: string | null;
    author?: string | null;
    image?: (number | null) | Media;
  };
  csrCommitments?:
    | {
        title: string;
        icon?: ('education' | 'welfare' | 'eco' | 'economy' | 'community' | 'safety') | null;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'siteSettings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'navbarSettings';
        value: number | NavbarSetting;
      } | null)
    | ({
        relationTo: 'footerSettings';
        value: number | FooterSetting;
      } | null)
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null)
    | ({
        relationTo: 'treks';
        value: number | Trek;
      } | null)
    | ({
        relationTo: 'blogPosts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'teamMembers';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'departures';
        value: number | Departure;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'contactPages';
        value: number | ContactPage;
      } | null)
    | ({
        relationTo: 'blogSettings';
        value: number | BlogSetting;
      } | null)
    | ({
        relationTo: 'companyPages';
        value: number | CompanyPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  customRole?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  permissions?:
    | T
    | {
        treks_read?: T;
        treks_create?: T;
        treks_update?: T;
        treks_delete?: T;
        regions_read?: T;
        regions_create?: T;
        regions_update?: T;
        regions_delete?: T;
        departures_read?: T;
        departures_create?: T;
        departures_update?: T;
        departures_delete?: T;
        blogPosts_read?: T;
        blogPosts_create?: T;
        blogPosts_update?: T;
        blogPosts_delete?: T;
        pages_read?: T;
        pages_create?: T;
        pages_update?: T;
        pages_delete?: T;
        faqs_read?: T;
        faqs_create?: T;
        faqs_update?: T;
        faqs_delete?: T;
        gallery_read?: T;
        gallery_create?: T;
        gallery_update?: T;
        gallery_delete?: T;
        testimonials_read?: T;
        testimonials_create?: T;
        testimonials_update?: T;
        testimonials_delete?: T;
        teamMembers_read?: T;
        teamMembers_create?: T;
        teamMembers_update?: T;
        teamMembers_delete?: T;
        bookings_read?: T;
        bookings_create?: T;
        bookings_update?: T;
        bookings_delete?: T;
        inquiries_read?: T;
        inquiries_create?: T;
        inquiries_update?: T;
        inquiries_delete?: T;
        payments_read?: T;
        payments_create?: T;
        payments_update?: T;
        payments_delete?: T;
        siteSettings_read?: T;
        siteSettings_update?: T;
        media_read?: T;
        media_create?: T;
        media_update?: T;
        media_delete?: T;
        users_read?: T;
        users_create?: T;
        users_update?: T;
        users_delete?: T;
        roles_read?: T;
        roles_create?: T;
        roles_update?: T;
        roles_delete?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  heroVideoUrl?: T;
  heroImage?: T;
  heroHeadline?: T;
  heroSubheadline?: T;
  stats?:
    | T
    | {
        clients?: T;
        years?: T;
        treks?: T;
        rating?: T;
      };
  contactInfo?:
    | T
    | {
        phone?: T;
        whatsapp?: T;
        email?: T;
        address?: T;
        mapCoordinates?: T;
      };
  emergencyNumbers?:
    | T
    | {
        number?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        youtube?: T;
        instagram?: T;
        facebook?: T;
        tiktok?: T;
      };
  affiliations?:
    | T
    | {
        name?: T;
        logo?: T;
        url?: T;
        id?: T;
      };
  headerSettings?:
    | T
    | {
        expertName?: T;
        expertPhone?: T;
        expertWhatsApp?: T;
        quickEmail?: T;
      };
  footerSettings?:
    | T
    | {
        bioText?: T;
        nepalHeadOfficeAddress?: T;
        nepalHeadOfficePhone?: T;
        ukBranchOfficeAddress?: T;
        ukBranchOfficePhone?: T;
        governmentRegNo?: T;
      };
  videoGallery?:
    | T
    | {
        youtubeId?: T;
        title?: T;
        trekName?: T;
        id?: T;
      };
  top5Treks?: T;
  paymentSettings?:
    | T
    | {
        enableStripe?: T;
        enablePaypal?: T;
        enableLocalWallets?: T;
        enableBankTransfer?: T;
        enableBookNowPayLater?: T;
        advancePaymentPercentage?: T;
      };
  blogsPageSettings?:
    | T
    | {
        coverImage?: T;
        title?: T;
        subtitle?: T;
      };
  reviewPlatforms?:
    | T
    | {
        name?: T;
        rating?: T;
        maxRating?: T;
        reviewsCount?: T;
        badgeText?: T;
        stars?: T;
        id?: T;
      };
  featuredTravelInfo?: T;
  allowIndexing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbarSettings_select".
 */
export interface NavbarSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  navigationMenu?:
    | T
    | {
        title?: T;
        type?: T;
        href?: T;
        dropdownStyle?: T;
        featuredTreks?: T;
        customLinks?:
          | T
          | {
              label?: T;
              href?: T;
              hide?: T;
              id?: T;
            };
        hide?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footerSettings_select".
 */
export interface FooterSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  backgroundImage?: T;
  bioText?: T;
  newsletterTitle?: T;
  emergencyTitle?: T;
  emergencyNumbers?:
    | T
    | {
        number?: T;
        id?: T;
      };
  whatsappNumber?: T;
  emails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  nepalOfficeAddress?: T;
  nepalOfficePhone?: T;
  ukOfficeAddress?: T;
  ukOfficePhone?: T;
  navigationMenu?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  acceptedPayments?:
    | T
    | {
        enableSectigo?: T;
        enablePaypal?: T;
        enableMastercard?: T;
        enableVisa?: T;
        enableSwift?: T;
      };
  affiliations?:
    | T
    | {
        name?: T;
        logo?: T;
        url?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        youtube?: T;
        instagram?: T;
        facebook?: T;
        tiktok?: T;
      };
  governmentRegNo?: T;
  copyrightNotice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  coverImage?: T;
  mapCenter?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treks_select".
 */
export interface TreksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  region?: T;
  difficulty?: T;
  price?: T;
  discountedPrice?: T;
  duration?: T;
  maxAltitude?: T;
  groupSize?: T;
  startPoint?: T;
  endPoint?: T;
  bestSeason?: T;
  accommodationType?: T;
  mealsIncluded?: T;
  isBestSeller?: T;
  highlights?:
    | T
    | {
        highlight?: T;
        id?: T;
      };
  overview?: T;
  flightInfoTitle?: T;
  flightInfo?: T;
  briefingInfo?: T;
  heroImage?: T;
  mapImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  youtubeVideoId?: T;
  dayByDayItinerary?:
    | T
    | {
        day?: T;
        title?: T;
        location?: T;
        distance?: T;
        altitude?: T;
        trekDuration?: T;
        flightHours?: T;
        description?: T;
        accommodation?: T;
        meals?: T;
        media?:
          | T
          | {
              type?: T;
              image?: T;
              youtubeUrl?: T;
              title?: T;
              id?: T;
            };
        id?: T;
      };
  inclusions?:
    | T
    | {
        heading?: T;
        icon?: T;
        points?:
          | T
          | {
              point?: T;
              id?: T;
            };
        id?: T;
      };
  exclusions?:
    | T
    | {
        heading?: T;
        icon?: T;
        points?:
          | T
          | {
              point?: T;
              id?: T;
            };
        id?: T;
      };
  packingList?:
    | T
    | {
        category?: T;
        items?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  tripInfoSections?:
    | T
    | {
        title?: T;
        icon?: T;
        content?: T;
        image?: T;
        id?: T;
      };
  gpsCoordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
        label?: T;
        altitude?: T;
        id?: T;
      };
  groupDiscounts?:
    | T
    | {
        minPersons?: T;
        maxPersons?: T;
        pricePerPerson?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        category?: T;
        answer?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  coverImage?: T;
  title?: T;
  body?: T;
  excerpt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
      };
  status?: T;
  publishedAt?: T;
  slug?: T;
  author?: T;
  category?: T;
  isFeatured?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedTreks?: T;
  wordCount?: T;
  readTime?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teamMembers_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        twitter?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  country?: T;
  rating?: T;
  reviewText?: T;
  trek?: T;
  date?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  category?: T;
  image?: T;
  caption?: T;
  trek?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  category?: T;
  treks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departures_select".
 */
export interface DeparturesSelect<T extends boolean = true> {
  trek?: T;
  startDate?: T;
  endDate?: T;
  availableSeats?: T;
  bookedSeats?: T;
  status?: T;
  priceOverride?: T;
  isGuaranteed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  bookingId?: T;
  trek?: T;
  departure?: T;
  startDate?: T;
  endDate?: T;
  travelersCount?: T;
  travelers?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        nationality?: T;
        gender?: T;
        dob?: T;
        passportNumber?: T;
        passportExpiry?: T;
        id?: T;
      };
  customerDetails?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
        country?: T;
      };
  basePrice?: T;
  discount?: T;
  tax?: T;
  totalPrice?: T;
  paymentType?: T;
  paymentStatus?: T;
  bookingStatus?: T;
  adminRemarks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  email?: T;
  phone?: T;
  country?: T;
  subject?: T;
  trek?: T;
  startDate?: T;
  travelers?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  booking?: T;
  paymentId?: T;
  amount?: T;
  method?: T;
  status?: T;
  transactionDetails?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  heroImage?: T;
  seoTitle?: T;
  seoDescription?: T;
  showInNavbar?: T;
  navbarCategory?: T;
  navbarOrder?: T;
  relatedTreks?: T;
  documents?: T;
  videos?:
    | T
    | {
        title?: T;
        youtubeUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPages_select".
 */
export interface ContactPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  heroImage?: T;
  seoTitle?: T;
  seoDescription?: T;
  relatedTreks?: T;
  documents?: T;
  videos?:
    | T
    | {
        title?: T;
        youtubeUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogSettings_select".
 */
export interface BlogSettingsSelect<T extends boolean = true> {
  coverImage?: T;
  title?: T;
  subtitle?: T;
  guideSettings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companyPages_select".
 */
export interface CompanyPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  heroImage?: T;
  seoTitle?: T;
  seoDescription?: T;
  relatedTreks?: T;
  documents?: T;
  legalCertificates?:
    | T
    | {
        title?: T;
        image?: T;
        id?: T;
      };
  teamMembers?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        bio?: T;
        socialLinks?:
          | T
          | {
              facebook?: T;
              instagram?: T;
              linkedin?: T;
              twitter?: T;
            };
        id?: T;
      };
  videos?:
    | T
    | {
        title?: T;
        youtubeUrl?: T;
        id?: T;
      };
  csrQuote?:
    | T
    | {
        text?: T;
        author?: T;
        image?: T;
      };
  csrCommitments?:
    | T
    | {
        title?: T;
        icon?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}